#ifndef __PINS_h_
#define __PINS_h_

#ifdef __USE_CMSIS
#include "LPC17xx.h"
#endif

#include "UMDLPC/util/pins.h"

//   P0.23 as AD0.0 (1 at bit 14)
//   P0.26 as AOUT  (2 at bit 20)

DEFINE_PIN(RECORDING_LED, 0, 22); // builtin LED
DEFINE_PIN(PLAYING_LED, 0, 21);
DEFINE_PIN(RECORD_BUTTON, 0, 2);
DEFINE_PIN(PLAY_BUTTON, 0, 3);

DEFINE_PIN(TFT_RS, 2, 12);
DEFINE_PIN(TFT_WR, 2, 11);
DEFINE_PIN(TFT_RD, 2, 10);
DEFINE_PIN(TFT_CS, 2, 8);
DEFINE_PIN(TFT_RST, 2, 7);

DEFINE_PIN(TFT_SHIFT_DATA, 2, 6);
DEFINE_PIN(TFT_SHIFT_CLOCK, 2, 5);
DEFINE_PIN(TFT_SHIFT_LATCH, 2, 4);

DEFINE_PIN(TOUCH_CLK, 2, 3);
DEFINE_PIN(TOUCH_IN, 2, 2);
DEFINE_PIN(TOUCH_BUSY, 0, 11);
DEFINE_PIN(TOUCH_OUT, 2, 1);
DEFINE_PIN(TOUCH_PENIRQ, 2, 13);

#endif
